### PR TITLE
Remove spaces size & fixed syntax errors in the process

### PR DESCRIPTION
**Pull request by acekyd**
Please check the syntax errors... if any has been misjudged... please let me know/edit.

### CODE REVIEW

**Comment by acekyd** [comment]
I went ahead to remove extra whitespaces with the hope of reducing file sizes in the long run... i'm not sure that was effective at the end of the day. @isocroft

**Comment by isocroft** [comment]
Thanks a lot for this PR especially the correction of syntax errors. I'll look into the merge conflict and resolve it before merging it in.

Much Appreciated !!

**Comment by shalvah** [comment]
I think this PR should be merged ASAP

**Comment by isocroft** [comment]
Already Merged !!

Thanks once again Guys !!

**Comment by acekyd** [comment]
Awesome... Glad to help @isocroft

**Pull request merged**
